version: '3.8'

services:
  kernelbench:
    build: .
    container_name: kernelbench-triton
    volumes:
      - .:/workspace
      - ~/.cache:/root/.cache  # Cache pip/huggingface downloads
    working_dir: /workspace
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - TRITON_PRINT_AUTOTUNING=1
    shm_size: '8gb'  # Increase shared memory for large models 