description: Full raw evaluation using locally-generated kernels and GROQ formatter.

modes:
  - raw

languages:
  - cuda

models:
  - provider: groq
    model: moonshotai/kimi-k2-instruct-0905

defaults:
  profile_stages: true
  raw:
    cpu_concurrency: max
    gpu_concurrency: 1
    max_jobs: max

verbose: true
profile_stages: true
fast_p_threshold: null
raw_concurrency: max
raw_gpu_concurrency: 1
raw_max_jobs: max

hardware:
  gpu_architecture: Ampere
  gpu_id: 0

problems:
  levels: [1, 2]
  problem_ids: null
  max_problems: null

modal:
  image:
    cuda_version: "12.8.1"
    os_tag: "ubuntu24.04"
    python_version: "3.12"
  gpu:
    name: "A100"
    count: 1
  timeouts:
    process_seconds: 0

artifacts:
  json_dir: json
  plots_dir: plots/raw

visualization:
  enabled: true
