description: Single-provider benchmark using Groq moonshotai/kimi-k2-instruct-0905 across raw & agentic modes.

modes:
  - raw
  - agentic

languages:
  - cuda
  - triton

models:
  - provider: groq
    model: moonshotai/kimi-k2-instruct-0905

defaults:
  profile_stages: true
  raw:
    cpu_concurrency: max
    gpu_concurrency: 2
    max_jobs: max

verbose: true
profile_stages: true
fast_p_threshold: null
raw_concurrency: max
raw_gpu_concurrency: 2
raw_max_jobs: max

hardware:
  gpu_architecture: Ampere
  gpu_id: 0

problems:
  levels: [1, 2]
  problem_ids: null
  max_problems: 100

agentic:
  max_debug_attempts: 3
  max_optimization_cycles: 2

artifacts:
  json_dir: json
  plots_dir: plots

visualization:
  enabled: false
